// import { Inter } from 'next/font/google'
 import './globals.css'
 import Api from "components/Api"
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'News App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
  <Api/>
      <body >{children}</body>
    </html>
  )
}
